### ISSUE TITLE
review do not work

### ISSUE THREAD

**Issue by Certseeds** [unsafecoerce/chatgpt-action#24]
please refer this actions, code review seems do not output anything.
<https://github.com/Certseeds/openpgpage/actions/runs/4316287005/jobs/7531859027>

**Comment by sighingnow** [comment]
Thanks for the feedback. Will take a look soon.

**Comment by Certseeds** [comment]
> Thanks for the feedback. Will take a look soon.
I found that's because this action need clone the repo, it's not a bug, but a feature.

**Comment by sighingnow** [comment]
What you do mean about "clone the repo"? It seems that there are issues with compute the diff hunks.

**Comment by Certseeds** [comment]
oh, it seems i wanna to open another issue to report the score action do not work, later find it depend on clone the repo. finally i close that, it a mistake, the old problem still in there and thernew one is a misunderstand.

**Comment by sighingnow** [comment]
Issue fixed.

Just try rerun your action.
